### ISSUE TITLE
Argument Error

### ISSUE THREAD

**Issue by petehinch** [amclain/netlinx-compile#10]
Hi, I can't seem to get Netlinx-compile to work. It returns the following

C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/netlinx-compile-3.1.1/lib/netlinx/source_file.rb:22:in `scan': invalid byte sequence in UTF-8 (ArgumentError)

Thanks

**Comment by amclain** [comment]
Thanks for the bug report!

I've fixed this in #13 and v3.1.2 has been released to rubygems.
